### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by utap2001** [GustavoKatel/pushbullet-cli#100]
excuse me everyone, 
how to deal with this error message when install the pushbullet-cli

  WARNING: The script keyring is installed in '/home/apple/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

  WARNING: The script pb is installed in '/home/apple/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Successfully installed SecretStorage-3.3.1 click-7.1.2 jeepney-0.6.0 keyring-21.4.0 keyrings-alt pushbullet-cli-1.2 pushbullet-py python-magic-0.4.18 websocket-client-0.57.0

**Comment by ReneFroger** [comment]
I have the same problem with the keyrings-alt as well.

**Comment by utap2001** [comment]
I havn't use the cli finally due to installation problems. But I found you can use pushbullet web API directly. More conveniently and simple and can bypass other unrelated problems. Great API  !!  Example: 

curl --header 'Access-Token: <token>' \
     --header 'Content-Type: application/json' \
     --data-binary '{"body":"open the calculator","title":"title","type":"note"}' \
     --request POST \
     https://api.pushbullet.com/v2/pushes

**Comment by GustavoKatel** [comment]
hi @utap2001 which python version are u using? also which OS?

**Comment by utap2001** [comment]
hi, python: 3.8.5
ubuntu: 20.04.1

**Comment by GustavoKatel** [comment]
@utap2001 I can think of two options to solve your issue:

1- Add `/home/apple/.local/bin` to you PATH with `echo "export PATH=/home/apple/.local/bin:$PATH" >> ~/.bashrc`
2- Install pushbullet-cli with root: `sudo pip3 install pushbullet-cli`

**Comment by utap2001** [comment]
Nice job, it worked !! 
Appreciate for your cli and solution, now the pushbullet eventually became well-behaved.
