### ISSUE TITLE
Is it possible to remove the "Note" prefix on pushes?

### ISSUE THREAD

**Issue by krompus** [GustavoKatel/pushbullet-cli#36]
When I push things with `pb push`, URLs for example, there is always a pesky "Note " before the content:

```
Note
http://sheldonbrown.com/
```

I would very much like to remove this entirely, as I currently remove it manually.

**Comment by GustavoKatel** [comment]
If it matter, you can use to `-t str` to set the note's title

It would be `pb push -t "My note" "Message"`

**Comment by krompus** [comment]
Ah, I'd like to remove it entirely, and push the bare URL.

**Comment by GustavoKatel** [comment]
Hi @krompus The version 0.7.6 should resolve this.

Until then you can try by installing from the develop branch: pip install git+https://github.com/GustavoKatel/pushbullet-cli.git@develop
