### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by r-darwish** [GustavoKatel/pushbullet-cli#38]
I no longer use Pushbullet. I am looking for someone to take over this project.

**Comment by GustavoKatel** [comment]
Hi, I'd be happy to help you out

**Comment by r-darwish** [comment]
@GustavoKatel if you delete your fork of the repository then I can make you the owner.

**Comment by GustavoKatel** [comment]
@r-darwish Done

**Comment by r-darwish** [comment]
I requested that the repository will be transferred. Please also give me your user name in pypi.python.org so I can make you the owner there as well

**Comment by GustavoKatel** [comment]
Pypi username: gustavokatel

**Comment by r-darwish** [comment]
Done
