### ISSUE TITLE
error unknow

### ISSUE THREAD

**Issue by Blacksly** [GustavoKatel/pushbullet-cli#39]
hi guys ! 
I have this error when i want use pushbullet-cli ... 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (setuptools 5.5.1 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=11.3'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: setuptools>=11.3

any idea ?? thank you

**Comment by GustavoKatel** [comment]
Hi @Blacksly 
Which python version are you using?

Also what is the version of your setuptools? You can run this command to see the version of setuptools
`pip show setuptools` (Python2.7)
`pip3 show setuptools` (Python 3)

**Comment by GustavoKatel** [comment]
This is weird. What's your OS? How did you install pip?

**Comment by Blacksly** [comment]
it's last version of raspbian, and i had install pip with apt-get command ^^
before i see pip install pushbullet-cli commande for install push bullet i tried : 
python3 setup.py install. 

Can that be the result?

**Comment by GustavoKatel** [comment]
Probably, try to remove your previous installation and reinstall from pip.

**Comment by Blacksly** [comment]
i tried, but i don't know how i can remove my first instalation ...

**Comment by GustavoKatel** [comment]
You probably have an egg in your `/usr/local/lib/python3.5/dist-packages/` corresponding to `pushbullet-cli`. Remove it.
Also check if you have the latest pip version with `pip install --upgrade pip` or `pip3 install --upgrade pip`

After that try to install again directly from pip

Feel free to ask you have problems

**Comment by GustavoKatel** [comment]
No answer. Feel free to try the new version and re-open this issue if any problems. Thanks
