### ISSUE TITLE
Newline not possible

### ISSUE THREAD

**Issue by sidneywidmer** [GustavoKatel/pushbullet-cli#42]
I tried `\n` and `\\n`and none arrived as newline. Is it possible to send a linefeed in a note?

**Comment by GustavoKatel** [comment]
You can achieve that by forcing your terminal to interpret `\n` as a new-line. Something like this would do it:
```sh
echo -e "This is\na new line" | pb push
```

From the `echo`'s man page:

> -e     enable interpretation of backslash escapes

**Comment by sidneywidmer** [comment]
Well, that was easy :) Thank you!
