### ISSUE TITLE
Characters like "æ","ø",å","ë","é","ä" breaks "pb list" (but not list-devices or push)

### ISSUE THREAD

**Issue by StefanBRas** [GustavoKatel/pushbullet-cli#43]
Hello! The picture shows the problem. The characters mentioned is probably not an exhaustive list of characters with this problem, just the ones i tested right now.
![pberror](https://user-images.githubusercontent.com/28559054/32273843-6aea5094-bf04-11e7-9f1d-e4f5bad2e3af.png)

As shown, "list-devices" has no trouble.

The input device doesn't matter - i pushed an "æ" from both Chrome, Android and PB CLI with the same result.

The biggest problem (for me) is probably that it not only breaks the specific push, but makes it impossible for "pb list" to retrieve any pushes, if they're pushed earlier than a push with one of these characters.

Pushbullet CLI Version 0.7.6
Python 2.7.12/3.5.2
Ubuntu 16.04 LTS

I won't mind trying to solve it on my own but i'll probably need a hint on what to do.

**Comment by oshank** [comment]
It would seem that it can't handle any ascii chars above 128. It might have something to do with the specific way the script decodes the string. Follow the traceback, it will bring you to app.py line 152 and 163.

**Comment by GustavoKatel** [comment]
I've just pushed a new version to PyPI which should fix this issue. Can you try with the new version? Feel free to re-open this issue, if any problems
