### ISSUE TITLE
Can't seem to push any text/link/file

### ISSUE THREAD

**Issue by johenkel** [GustavoKatel/pushbullet-cli#59]
I am using pushbullet-cli v 0.7.6 on Ubuntu 18.04 / python 3.5

I can use pb to send  a text message (sms) but cannot use it to push simple text/link or a file. It throws an error shown below:

`johenkel@localhost:~$ pb list-devices
0. Chrome
1. Motorola XT1585

johenkel@localhost:~$ pb push "test"
Traceback (most recent call last):
  File "/usr/local/bin/pb", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: push() got an unexpected keyword argument 'file'`

Not sure where to start to figure the problem. Any help would be appreciated.

**Comment by caltlgin** [comment]
Thanks @Twizzes. Got it working in Ubuntu with the following code, adapted from your comment.

```sh
git clone --depth=1 https://github.com/GustavoKatel/pushbullet-cli.git && \
cd ~/pushbullet-cli && \
python setup.py install --user && \
rm -rfv ~/pushbullet-cli
```

**Comment by GustavoKatel** [comment]
Thank you for pointing this. There's a compatibility issue with some `Click` versions. I have fixed in the repo, but I didn't had time to release in PyPI yet. I should upload it soon tho.

**Comment by GustavoKatel** [comment]
I've just pushed a new version to PyPi. Feel free to install from it, if you'd like and re-open this issue if any problems. Thanks :)
