### ISSUE TITLE
Bump keyring version

### ISSUE THREAD

**Issue by jmarrec** [GustavoKatel/pushbullet-cli#83]
pypi has keyring 21.2.1 now, while setup.py has 

https://github.com/GustavoKatel/pushbullet-cli/blob/97b02375ad07be1b297c569ecbe8eef146f3197f/setup.py#L23

It also seems that the version 1.1 in the changelog was actually not released (not tagged here, and not on pypi), so you get this:

```
pushbullet-cli 1.0 has requirement keyring~=16.0.2, but you have keyring 21.2.1.
```

Thanks for the useful CLI!

**Comment by ReneFroger** [comment]
I have the same problem with the keyring, Pip cannot find the right version.
